/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './seo';
const styles_ComponentViewSeo:any[] = ([] as any[]);
export const RenderType_ComponentViewSeo:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ComponentViewSeo,data:{}});
export function View_ComponentViewSeo_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),0,'div',([] as any[]),[[8,'innerHTML',1]],(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n']))],(null as any),
      (_ck,_v) => {
        var _co:i1.ComponentViewSeo = _v.component;
        const currVal_0:any = _co.seo;
        _ck(_v,1,0,currVal_0);
      });
}
export function View_ComponentViewSeo_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'v-seo',([] as any[]),
      (null as any),(null as any),(null as any),View_ComponentViewSeo_0,RenderType_ComponentViewSeo)),
      i0.ɵdid(49152,(null as any),0,i1.ComponentViewSeo,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const ComponentViewSeoNgFactory:i0.ComponentFactory<i1.ComponentViewSeo> = i0.ɵccf('v-seo',
    i1.ComponentViewSeo,View_ComponentViewSeo_Host_0,{seo:'seo'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvdmlldy9jb21wb25lbnRzL3Nlby9zZW8ubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvdmlldy9jb21wb25lbnRzL3Nlby9zZW8udHMiLCJuZzovLy9DOi9Qcm9qZWN0cy9tYXJrZXQvbWFya2V0L2NsaWVudC93ZWIvYXBwMS9wYWdlcy92aWV3L2NvbXBvbmVudHMvc2VvL3Nlby50cy5Db21wb25lbnRWaWV3U2VvLmh0bWwiLCJuZzovLy9DOi9Qcm9qZWN0cy9tYXJrZXQvbWFya2V0L2NsaWVudC93ZWIvYXBwMS9wYWdlcy92aWV3L2NvbXBvbmVudHMvc2VvL3Nlby50cy5Db21wb25lbnRWaWV3U2VvX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG48ZGl2IFtpbm5lckh0bWxdPVwic2VvXCI+PC9kaXY+XG4iLCI8di1zZW8+PC92LXNlbz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQSx1Q0FDQTtNQUFBO01BQUEsOEJBQTZCOzs7UUFBeEI7UUFBTCxXQUFLLFNBQUw7Ozs7b0JDREE7TUFBQTthQUFBO1VBQUE7OzsifQ==
