/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../product/product.ngfactory';
import * as i2 from '@angular/common';
import * as i3 from '../product/product';
import * as i4 from './products';
const styles_ComponentSpecialsProducts:any[] = ([] as any[]);
export const RenderType_ComponentSpecialsProducts:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ComponentSpecialsProducts,data:{}});
function View_ComponentSpecialsProducts_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),3,'sp-product',[['class',
      'special-product mm-special col-lg-3 col-md-4 col-sm-6 col-12 product']],(null as any),
      [[(null as any),'onPostPosition']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:any = _v.component;
        if (('onPostPosition' === en)) {
          const pd_0:any = ((<any>_co.postPosition($event)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },i1.View_ComponentSpecialsProduct_0,i1.RenderType_ComponentSpecialsProduct)),
      i0.ɵdid(278528,(null as any),0,i2.NgClass,[i0.IterableDiffers,i0.KeyValueDiffers,
          i0.ElementRef,i0.Renderer],{klass:[0,'klass'],ngClass:[1,'ngClass']},(null as any)),
      i0.ɵpod({'hidden-sm-down hidden-lg-up':0}),i0.ɵdid(49152,(null as any),0,i3.ComponentSpecialsProduct,
          ([] as any[]),{product:[0,'product']},{onPostPosition:'onPostPosition'})],
      (_ck,_v) => {
        const currVal_0:any = 'special-product mm-special col-lg-3 col-md-4 col-sm-6 col-12';
        const currVal_1:any = _ck(_v,2,0,_v.context.last);
        _ck(_v,1,0,currVal_0,currVal_1);
        const currVal_2:any = _v.context.$implicit;
        _ck(_v,3,0,currVal_2);
      },(null as any));
}
export function View_ComponentSpecialsProducts_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h2',[['class',
      'col-12']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['Самое интересное'])),(_l()(),i0.ɵted((null as any),
          ['\n'])),(_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),
          View_ComponentSpecialsProducts_1)),i0.ɵdid(802816,(null as any),0,i2.NgForOf,
          [i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],{ngForOf:[0,'ngForOf']},
          (null as any))],(_ck,_v) => {
    var _co:i4.ComponentSpecialsProducts = _v.component;
    const currVal_0:any = _co.products;
    _ck(_v,4,0,currVal_0);
  },(null as any));
}
export function View_ComponentSpecialsProducts_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'sp-products',
      ([] as any[]),(null as any),(null as any),(null as any),View_ComponentSpecialsProducts_0,
      RenderType_ComponentSpecialsProducts)),i0.ɵdid(49152,(null as any),0,i4.ComponentSpecialsProducts,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const ComponentSpecialsProductsNgFactory:i0.ComponentFactory<i4.ComponentSpecialsProducts> = i0.ɵccf('sp-products',
    i4.ComponentSpecialsProducts,View_ComponentSpecialsProducts_Host_0,{products:'products'},
    {onPostPosition:'onPostPosition'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvc3BlY2lhbHMvY29tcG9uZW50cy9wcm9kdWN0cy9wcm9kdWN0cy5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Qcm9qZWN0cy9tYXJrZXQvbWFya2V0L2NsaWVudC93ZWIvYXBwMS9wYWdlcy9zcGVjaWFscy9jb21wb25lbnRzL3Byb2R1Y3RzL3Byb2R1Y3RzLnRzIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvc3BlY2lhbHMvY29tcG9uZW50cy9wcm9kdWN0cy9wcm9kdWN0cy5odG1sIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvc3BlY2lhbHMvY29tcG9uZW50cy9wcm9kdWN0cy9wcm9kdWN0cy50cy5Db21wb25lbnRTcGVjaWFsc1Byb2R1Y3RzX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgyIGNsYXNzPVwiY29sLTEyXCI+0KHQsNC80L7QtSDQuNC90YLQtdGA0LXRgdC90L7QtTwvaDI+XHJcbjxzcC1wcm9kdWN0IGNsYXNzPVwic3BlY2lhbC1wcm9kdWN0IG1tLXNwZWNpYWwgY29sLWxnLTMgY29sLW1kLTQgY29sLXNtLTYgY29sLTEyXCJcclxuICAgICAgICAgICAgKG9uUG9zdFBvc2l0aW9uKT1cInBvc3RQb3NpdGlvbigkZXZlbnQpXCJcclxuICAgICAgICAgICAgW25nQ2xhc3NdPVwieydoaWRkZW4tc20tZG93biBoaWRkZW4tbGctdXAnOmxhc3R9XCJcclxuICAgICAgICAgICAgKm5nRm9yPVwibGV0IHByb2R1Y3Qgb2YgcHJvZHVjdHM7IGxldCBsYXN0ID0gbGFzdDtcIlxyXG4gICAgICAgICAgICBbcHJvZHVjdF09XCJwcm9kdWN0XCI+PC9zcC1wcm9kdWN0PiIsIjxzcC1wcm9kdWN0cz48L3NwLXByb2R1Y3RzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0NBO01BQUE7TUFBQTtRQUFBO1FBQUE7UUFDWTtVQUFBO1VBQUE7UUFBQTtRQURaO01BQUE7YUFBQTttQ0FBQTthQUVZLDJDQUZaO1VBQUE7O1FBQVk7UUFFQTtRQUZaLFdBQVksVUFFQSxTQUZaO1FBSVk7UUFKWixXQUlZLFNBSlo7Ozs7b0JBREE7TUFBQTtNQUFtQixxREFBcUI7VUFBQSxTQUN4QztVQUFBLDBDQUFBO1VBQUE7VUFBQTs7SUFHWTtJQUhaLFdBR1ksU0FIWjs7OztvQkNEQTtNQUFBOzBDQUFBLFVBQUE7TUFBQTs7OzsifQ==
