/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './module';
import * as i2 from '../layouts/default.ngfactory';
import * as i3 from './specials/specials.ngfactory';
import * as i4 from './delivery/delivery.ngfactory';
import * as i5 from './contacts/contacts.ngfactory';
import * as i6 from './cart/cart/cart.ngfactory';
import * as i7 from './cart/history/history.ngfactory';
import * as i8 from './stocks/stocks.ngfactory';
import * as i9 from './notfound/page-notfound.ngfactory';
import * as i10 from './view/view.ngfactory';
import * as i11 from './catalog/catalog.ngfactory';
import * as i12 from '@angular/common';
import * as i13 from '@angular/platform-browser';
import * as i14 from '@angular/animations/browser';
import * as i15 from '@angular/platform-browser/animations';
import * as i16 from '@angular/animations';
import * as i17 from '@angular/forms';
import * as i18 from '@angular/router';
import * as i19 from '../layouts/default';
import * as i20 from './specials/specials';
import * as i21 from './delivery/delivery';
import * as i22 from './contacts/contacts';
import * as i23 from './cart/cart/cart';
import * as i24 from './cart/history/history';
import * as i25 from './stocks/stocks';
import * as i26 from './notfound/page-notfound';
import * as i27 from './view/view';
import * as i28 from './catalog/catalog';
import * as i29 from '../controls/module';
import * as i30 from './specials/components/module';
import * as i31 from './view/components/module';
import * as i32 from './cart/components/module';
import * as i33 from './catalog/components/module';
export const PagesModuleNgFactory:i0.NgModuleFactory<i1.PagesModule> = i0.ɵcmf(i1.PagesModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.DefaultLayoutNgFactory,i3.SpecialsPageNgFactory,i4.DeliveryPageNgFactory,
              i5.ContactsPageNgFactory,i6.CartPageNgFactory,i7.HistoryPageNgFactory,
              i8.StocksPageNgFactory,i9.NotfoundPageNgFactory,i10.ViewPageNgFactory,
              i11.CatalogPageNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i12.NgLocalization,
              i12.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,
              ([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i13.DomSanitizer,
              i13.ɵe,[i12.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i13.DomSanitizer]),
          i0.ɵmpd(4608,i13.HAMMER_GESTURE_CONFIG,i13.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i13.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i13.ɵDomEventsPlugin(p0_0),new i13.ɵKeyEventsPlugin(p1_0),
                new i13.ɵHammerGesturesPlugin(p2_0,p2_1)];
          },[i12.DOCUMENT,i12.DOCUMENT,i12.DOCUMENT,i13.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i13.EventManager,i13.EventManager,[i13.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i13.ɵDomSharedStylesHost,i13.ɵDomSharedStylesHost,[i12.DOCUMENT]),
          i0.ɵmpd(4608,i13.ɵDomRendererFactory2,i13.ɵDomRendererFactory2,[i13.EventManager,
              i13.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i14.AnimationDriver,i15.ɵc,([] as any[])),
          i0.ɵmpd(5120,i14.ɵAnimationStyleNormalizer,i15.ɵd,([] as any[])),i0.ɵmpd(4608,
              i14.ɵAnimationEngine,i15.ɵb,[i14.AnimationDriver,i14.ɵAnimationStyleNormalizer]),
          i0.ɵmpd(5120,i0.RendererFactory2,i15.ɵe,[i13.ɵDomRendererFactory2,i14.ɵAnimationEngine,
              i0.NgZone]),i0.ɵmpd(6144,i13.ɵSharedStylesHost,(null as any),[i13.ɵDomSharedStylesHost]),
          i0.ɵmpd(4608,i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i13.Meta,
              i13.Meta,[i12.DOCUMENT]),i0.ɵmpd(4608,i13.Title,i13.Title,[i12.DOCUMENT]),
          i0.ɵmpd(4608,i16.AnimationBuilder,i15.ɵBrowserAnimationBuilder,[i0.RendererFactory2,
              i13.DOCUMENT]),i0.ɵmpd(4608,i17.ɵi,i17.ɵi,([] as any[])),i0.ɵmpd(5120,
              i18.ActivatedRoute,i18.ɵf,[i18.Router]),i0.ɵmpd(4608,i18.NoPreloading,
              i18.NoPreloading,([] as any[])),i0.ɵmpd(6144,i18.PreloadingStrategy,
              (null as any),[i18.NoPreloading]),i0.ɵmpd(135680,i18.RouterPreloader,
              i18.RouterPreloader,[i18.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i18.PreloadingStrategy]),i0.ɵmpd(4608,i18.PreloadAllModules,
              i18.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i18.ROUTER_INITIALIZER,
              i18.ɵi,[i18.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i18.ROUTER_INITIALIZER]),i0.ɵmpd(512,i12.CommonModule,i12.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i13.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i18.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i18.ɵg,i18.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i13.ɵc(p0_0,p0_1),i18.ɵh(p1_0)];
              },[[2,i13.NgProbeToken],[2,i0.NgProbeToken],i18.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i13.BrowserModule,i13.BrowserModule,[[3,i13.BrowserModule]]),
          i0.ɵmpd(512,i15.BrowserAnimationsModule,i15.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(1024,i18.ɵa,i18.ɵd,[[3,i18.Router]]),i0.ɵmpd(512,i18.UrlSerializer,
              i18.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i18.ChildrenOutletContexts,
              i18.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i18.ROUTER_CONFIGURATION,
              {},([] as any[])),i0.ɵmpd(1024,i12.LocationStrategy,i18.ɵc,[i12.PlatformLocation,
              [2,i12.APP_BASE_HREF],i18.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i12.Location,
              i12.Location,[i12.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i18.ROUTES,
              () => {
                return [[{path:'',component:i19.DefaultLayout,children:[{path:'',component:i20.SpecialsPage},
                    {path:'delivery',component:i21.DeliveryPage},{path:'contacts',
                        component:i22.ContactsPage},{path:'cart',component:i23.CartPage},
                    {path:'cart/:contract',component:i24.HistoryPage},{path:'stocks',
                        component:i25.StocksPage},{path:'notfound',component:i26.NotfoundPage},
                    {path:':categoryName/:productId',component:i27.ViewPage},{path:':categoryName',
                        component:i28.CatalogPage},{path:'**',redirectTo:'/notfound'}]}]];
              },([] as any[])),i0.ɵmpd(1024,i18.Router,i18.ɵe,[i0.ApplicationRef,i18.UrlSerializer,
              i18.ChildrenOutletContexts,i12.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i18.ROUTES,i18.ROUTER_CONFIGURATION,[2,i18.UrlHandlingStrategy],
              [2,i18.RouteReuseStrategy]]),i0.ɵmpd(512,i18.RouterModule,i18.RouterModule,
              [[2,i18.ɵa],[2,i18.Router]]),i0.ɵmpd(512,i29.ControlsModule,i29.ControlsModule,
              ([] as any[])),i0.ɵmpd(512,i30.ModuleComponentsSpecials,i30.ModuleComponentsSpecials,
              ([] as any[])),i0.ɵmpd(512,i31.ModuleComponentsView,i31.ModuleComponentsView,
              ([] as any[])),i0.ɵmpd(512,i17.ɵba,i17.ɵba,([] as any[])),i0.ɵmpd(512,
              i17.FormsModule,i17.FormsModule,([] as any[])),i0.ɵmpd(512,i32.ModuleComponentsCart,
              i32.ModuleComponentsCart,([] as any[])),i0.ɵmpd(512,i33.ModuleComponentsCatalog,
              i33.ModuleComponentsCatalog,([] as any[])),i0.ɵmpd(512,i1.PagesModule,
              i1.PagesModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvbW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL3BhZ2VzL21vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
