/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './information';
const styles_ComponentViewInformation:any[] = ([] as any[]);
export const RenderType_ComponentViewInformation:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ComponentViewInformation,data:{}});
export function View_ComponentViewInformation_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['    \n'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Описание'])),(_l()(),
      i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
      0,'p',([] as any[]),[[8,'innerHTML',1]],(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['\n']))],(null as any),(_ck,_v) => {
    var _co:i1.ComponentViewInformation = _v.component;
    const currVal_0:any = _co.information;
    _ck(_v,4,0,currVal_0);
  });
}
export function View_ComponentViewInformation_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'v-information',
      [['class','me-info col-md-12 col-lg-6']],(null as any),(null as any),(null as any),
      View_ComponentViewInformation_0,RenderType_ComponentViewInformation)),i0.ɵdid(49152,
      (null as any),0,i1.ComponentViewInformation,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const ComponentViewInformationNgFactory:i0.ComponentFactory<i1.ComponentViewInformation> = i0.ɵccf('v-information',
    i1.ComponentViewInformation,View_ComponentViewInformation_Host_0,{information:'information'},
    {},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvdmlldy9jb21wb25lbnRzL2luZm9ybWF0aW9uL2luZm9ybWF0aW9uLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL3BhZ2VzL3ZpZXcvY29tcG9uZW50cy9pbmZvcm1hdGlvbi9pbmZvcm1hdGlvbi50cyIsIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL3BhZ2VzL3ZpZXcvY29tcG9uZW50cy9pbmZvcm1hdGlvbi9pbmZvcm1hdGlvbi50cy5Db21wb25lbnRWaWV3SW5mb3JtYXRpb24uaHRtbCIsIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL3BhZ2VzL3ZpZXcvY29tcG9uZW50cy9pbmZvcm1hdGlvbi9pbmZvcm1hdGlvbi50cy5Db21wb25lbnRWaWV3SW5mb3JtYXRpb25fSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCIgICAgXG48aDI+0J7Qv9C40YHQsNC90LjQtTwvaDI+XG48cCBbaW5uZXJIVE1MXT1cImluZm9ybWF0aW9uXCI+PC9wPlxuIiwiPHYtaW5mb3JtYXRpb24+PC92LWluZm9ybWF0aW9uPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDJDQUNBO01BQUE7TUFBQSw4QkFBSSw2Q0FBYTthQUFBLHdCQUNqQjtNQUFBO01BQUEsZ0JBQWlDOztJQUE5QjtJQUFILFdBQUcsU0FBSDs7OztvQkNGQTtNQUFBO3lFQUFBLFVBQUE7TUFBQTs7Ozs7In0=
