/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './title';
const styles_ComponentViewTitle:any[] = ([] as any[]);
export const RenderType_ComponentViewTitle:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ComponentViewTitle,data:{}});
function View_ComponentViewTitle_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),3,'a',[['class',
      'btn btn-red pull-right m-back']],(null as any),[[(null as any),'click']],(_v,
      en,$event) => {
    var ad:boolean = true;
    var _co:any = _v.component;
    if (('click' === en)) {
      const pd_0:any = ((<any>_co.back()) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),0,'i',[['class','fa fa-chevron-left rgap']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['Назад\n']))],(null as any),(null as any));
}
export function View_ComponentViewTitle_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵand(16777216,
      (null as any),(null as any),1,(null as any),View_ComponentViewTitle_1)),i0.ɵdid(16384,
      (null as any),0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,'ngIf']},
      (null as any)),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'h1',[['class','me-name']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['',''])),(_l()(),
      i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
      0,'div',([] as any[]),[[8,'innerHTML',1]],(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    var _co:i2.ComponentViewTitle = _v.component;
    const currVal_0:any = _co.isBack;
    _ck(_v,2,0,currVal_0);
  },(_ck,_v) => {
    var _co:i2.ComponentViewTitle = _v.component;
    const currVal_1:any = _co.name;
    _ck(_v,5,0,currVal_1);
    const currVal_2:any = _co.details;
    _ck(_v,7,0,currVal_2);
  });
}
export function View_ComponentViewTitle_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'v-title',[['class',
      'me-info col-xs-12']],(null as any),(null as any),(null as any),View_ComponentViewTitle_0,
      RenderType_ComponentViewTitle)),i0.ɵdid(49152,(null as any),0,i2.ComponentViewTitle,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const ComponentViewTitleNgFactory:i0.ComponentFactory<i2.ComponentViewTitle> = i0.ɵccf('v-title',
    i2.ComponentViewTitle,View_ComponentViewTitle_Host_0,{name:'name',details:'details',
        isBack:'isBack'},{onBack:'onBack'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvdmlldy9jb21wb25lbnRzL3RpdGxlL3RpdGxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL3BhZ2VzL3ZpZXcvY29tcG9uZW50cy90aXRsZS90aXRsZS50cyIsIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL3BhZ2VzL3ZpZXcvY29tcG9uZW50cy90aXRsZS90aXRsZS50cy5Db21wb25lbnRWaWV3VGl0bGUuaHRtbCIsIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL3BhZ2VzL3ZpZXcvY29tcG9uZW50cy90aXRsZS90aXRsZS50cy5Db21wb25lbnRWaWV3VGl0bGVfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbjxhIChjbGljayk9XCJiYWNrKClcIiAqbmdJZj1cImlzQmFja1wiIGNsYXNzPVwiYnRuIGJ0bi1yZWQgcHVsbC1yaWdodCBtLWJhY2tcIj5cbiAgICA8aSBjbGFzcz1cImZhIGZhLWNoZXZyb24tbGVmdCByZ2FwXCI+PC9pPtCd0LDQt9Cw0LRcbjwvYT5cbjxoMSBjbGFzcz1cIm1lLW5hbWVcIiA+e3tuYW1lfX08L2gxPlxuPGRpdiBbaW5uZXJIdG1sXT1cImRldGFpbHNcIj48L2Rpdj5cbiIsIjx2LXRpdGxlPjwvdi10aXRsZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQ0E7TUFBQTtlQUFBO0lBQUE7SUFBQTtJQUFHO01BQUE7TUFBQTtJQUFBO0lBQUg7RUFBQSxnQ0FBeUUsMkNBQ3JFO2FBQUE7VUFBQTtNQUF1Qzs7O29CQUYzQyx1Q0FDQTtNQUFBLCtFQUFBO01BQUE7TUFBQSxlQUVJLHVDQUNKO01BQUE7TUFBQSw4QkFBcUIsd0NBQWE7YUFBQSx3QkFDbEM7TUFBQTtNQUFBLGdCQUFpQzs7SUFKYjtJQUFwQixXQUFvQixTQUFwQjs7O0lBR3FCO0lBQUE7SUFDaEI7SUFBTCxXQUFLLFNBQUw7Ozs7b0JDTEE7TUFBQTttQ0FBQSxVQUFBO01BQUE7Ozs7In0=
