/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './promo';
const styles_ComponentSpecialsPromo:any[] = ([] as any[]);
export const RenderType_ComponentSpecialsPromo:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ComponentSpecialsPromo,data:{}});
export function View_ComponentSpecialsPromo_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h2',[['class',
      'col-12']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['Рекламная акция'])),(_l()(),i0.ɵted((null as any),
          ['\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p',[['class','col-12']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['Скидки в феврале!']))],(null as any),(null as any));
}
export function View_ComponentSpecialsPromo_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'sp-promo',([] as any[]),
      (null as any),(null as any),(null as any),View_ComponentSpecialsPromo_0,RenderType_ComponentSpecialsPromo)),
      i0.ɵdid(49152,(null as any),0,i1.ComponentSpecialsPromo,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const ComponentSpecialsPromoNgFactory:i0.ComponentFactory<i1.ComponentSpecialsPromo> = i0.ɵccf('sp-promo',
    i1.ComponentSpecialsPromo,View_ComponentSpecialsPromo_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvc3BlY2lhbHMvY29tcG9uZW50cy9wcm9tby9wcm9tby5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Qcm9qZWN0cy9tYXJrZXQvbWFya2V0L2NsaWVudC93ZWIvYXBwMS9wYWdlcy9zcGVjaWFscy9jb21wb25lbnRzL3Byb21vL3Byb21vLnRzIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvc3BlY2lhbHMvY29tcG9uZW50cy9wcm9tby9wcm9tby5odG1sIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvc3BlY2lhbHMvY29tcG9uZW50cy9wcm9tby9wcm9tby50cy5Db21wb25lbnRTcGVjaWFsc1Byb21vX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgyIGNsYXNzPVwiY29sLTEyXCI+0KDQtdC60LvQsNC80L3QsNGPINCw0LrRhtC40Y88L2gyPlxyXG48cCBjbGFzcz1cImNvbC0xMlwiPtCh0LrQuNC00LrQuCDQsiDRhNC10LLRgNCw0LvQtSE8L3A+IiwiPHNwLXByb21vPjwvc3AtcHJvbW8+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFtQixvREFBb0I7VUFBQSxTQUN2QztVQUFBO01BQWtCOzs7b0JDRGxCO01BQUE7YUFBQTtVQUFBOzs7In0=
