/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './progress';
const styles_ProgressControl:any[] = ([] as any[]);
export const RenderType_ProgressControl:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ProgressControl,data:{}});
export function View_ProgressControl_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['progress']))],(null as any),(null as any));
}
export function View_ProgressControl_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'progress',([] as any[]),
      (null as any),(null as any),(null as any),View_ProgressControl_0,RenderType_ProgressControl)),
      i0.ɵdid(49152,(null as any),0,i1.ProgressControl,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const ProgressControlNgFactory:i0.ComponentFactory<i1.ProgressControl> = i0.ɵccf('progress',
    i1.ProgressControl,View_ProgressControl_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvY29udHJvbHMvcHJvZ3Jlc3MvcHJvZ3Jlc3MubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvY29udHJvbHMvcHJvZ3Jlc3MvcHJvZ3Jlc3MudHMiLCJuZzovLy9DOi9Qcm9qZWN0cy9tYXJrZXQvbWFya2V0L2NsaWVudC93ZWIvYXBwMS9jb250cm9scy9wcm9ncmVzcy9wcm9ncmVzcy50cy5Qcm9ncmVzc0NvbnRyb2wuaHRtbCIsIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL2NvbnRyb2xzL3Byb2dyZXNzL3Byb2dyZXNzLnRzLlByb2dyZXNzQ29udHJvbF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsInByb2dyZXNzIiwiPHByb2dyZXNzPjwvcHJvZ3Jlc3M+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7OztvQkNBQTtNQUFBO2FBQUE7VUFBQTs7OyJ9
