/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '@angular/common';
import * as i3 from './navbar-brand';
const styles_NavbarBrandComponent:any[] = ([] as any[]);
export const RenderType_NavbarBrandComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_NavbarBrandComponent,data:{}});
export function View_NavbarBrandComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),6,'a',[['class',
      'navbar-brand__link'],['routerLinkActive','active']],[[1,'target',0],[8,'href',
      4]],[[(null as any),'click']],(_v,en,$event) => {
    var ad:boolean = true;
    if (('click' === en)) {
      const pd_0:any = ((<any>i0.ɵnov(_v,1).onClick($event.button,$event.ctrlKey,$event.metaKey,
          $event.shiftKey)) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any))),i0.ɵdid(671744,[[2,4]],0,i1.RouterLinkWithHref,[i1.Router,
      i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},(null as any)),
      i0.ɵdid(1720320,(null as any),2,i1.RouterLinkActive,[i1.Router,i0.ElementRef,
          i0.Renderer2,i0.ChangeDetectorRef],{routerLinkActive:[0,'routerLinkActive']},
          (null as any)),i0.ɵqud(603979776,1,{links:1}),i0.ɵqud(603979776,2,{linksWithHrefs:1}),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),0,'i',([] as any[]),[[8,'className',
          0]],(null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['',''])),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'b',[['class','navbar-brand__label']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['','']))],(_ck,_v) => {
    var _co:i3.NavbarBrandComponent = _v.component;
    const currVal_2:any = i0.ɵinlineInterpolate(1,'',_co.data.link,'');
    _ck(_v,1,0,currVal_2);
    const currVal_3:any = 'active';
    _ck(_v,2,0,currVal_3);
  },(_ck,_v) => {
    var _co:i3.NavbarBrandComponent = _v.component;
    const currVal_0:any = i0.ɵnov(_v,1).target;
    const currVal_1:any = i0.ɵnov(_v,1).href;
    _ck(_v,0,0,currVal_0,currVal_1);
    const currVal_4:any = i0.ɵinlineInterpolate(1,'fa ',_co.data.icon,' rgap');
    _ck(_v,5,0,currVal_4);
    const currVal_5:any = _co.data.name;
    _ck(_v,6,0,currVal_5);
    const currVal_6:any = _co.data.label;
    _ck(_v,9,0,currVal_6);
  });
}
export function View_NavbarBrandComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'navbar-brand',
      ([] as any[]),(null as any),(null as any),(null as any),View_NavbarBrandComponent_0,
      RenderType_NavbarBrandComponent)),i0.ɵdid(49152,(null as any),0,i3.NavbarBrandComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const NavbarBrandComponentNgFactory:i0.ComponentFactory<i3.NavbarBrandComponent> = i0.ɵccf('navbar-brand',
    i3.NavbarBrandComponent,View_NavbarBrandComponent_Host_0,{data:'data'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvY29udHJvbHMvbmF2YmFyL2NvbXBvbmVudHMvbmF2YmFyLWJyYW5kL25hdmJhci1icmFuZC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Qcm9qZWN0cy9tYXJrZXQvbWFya2V0L2NsaWVudC93ZWIvYXBwMS9jb250cm9scy9uYXZiYXIvY29tcG9uZW50cy9uYXZiYXItYnJhbmQvbmF2YmFyLWJyYW5kLnRzIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvY29udHJvbHMvbmF2YmFyL2NvbXBvbmVudHMvbmF2YmFyLWJyYW5kL25hdmJhci1icmFuZC5odG1sIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvY29udHJvbHMvbmF2YmFyL2NvbXBvbmVudHMvbmF2YmFyLWJyYW5kL25hdmJhci1icmFuZC50cy5OYXZiYXJCcmFuZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxhIGNsYXNzPVwibmF2YmFyLWJyYW5kX19saW5rXCIgcm91dGVyTGlua0FjdGl2ZT1cImFjdGl2ZVwiIHJvdXRlckxpbms9XCJ7e2RhdGEubGlua319XCI+PGkgY2xhc3M9XCJmYSB7e2RhdGEuaWNvbn19IHJnYXBcIj48L2k+e3tkYXRhLm5hbWV9fTwvYT5cclxuPGIgY2xhc3M9XCJuYXZiYXItYnJhbmRfX2xhYmVsXCI+e3tkYXRhLmxhYmVsfX08L2I+IiwiPG5hdmJhci1icmFuZD48L25hdmJhci1icmFuZD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBQTtJQUFBO0lBQUE7TUFBQTtVQUFBO01BQUE7SUFBQTtJQUFBO0VBQUEsdUNBQUE7MkNBQUE7YUFBQTsyQ0FBQTtVQUFBO01BQW1GO1VBQUEsOERBQXFDO1VBQUEsVUFBaUIsdUNBQ3pJO1VBQUE7VUFBQSw0Q0FBK0I7VUFBQTs7SUFEeUI7SUFBeEQsV0FBd0QsU0FBeEQ7SUFBOEI7SUFBOUIsV0FBOEIsU0FBOUI7OztJQUFBO0lBQUE7SUFBQSxXQUFBLG1CQUFBO0lBQXNGO0lBQUgsV0FBRyxTQUFIO0lBQXFDO0lBQUE7SUFDekY7SUFBQTs7OztvQkNEL0I7TUFBQTtxQ0FBQSxVQUFBO01BQUE7OzsifQ==
