/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './alert';
const styles_ComponentCatalogAlert:any[] = ([] as any[]);
export const RenderType_ComponentCatalogAlert:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ComponentCatalogAlert,data:{}});
export function View_ComponentCatalogAlert_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['Не найдено ни одного товара. Попробуйте изменить параметры поиска или '])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),1,'a',[['class','pointer text-nowrap']],
          (null as any),[[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            var _co:i1.ComponentCatalogAlert = _v.component;
            if (('click' === en)) {
              const pd_0:any = ((<any>_co.clearFilter()) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['сбросить фильтры']))],
      (null as any),(null as any));
}
export function View_ComponentCatalogAlert_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'cat-alert',[['class',
      'alert alert-info']],(null as any),(null as any),(null as any),View_ComponentCatalogAlert_0,
      RenderType_ComponentCatalogAlert)),i0.ɵdid(49152,(null as any),0,i1.ComponentCatalogAlert,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const ComponentCatalogAlertNgFactory:i0.ComponentFactory<i1.ComponentCatalogAlert> = i0.ɵccf('cat-alert',
    i1.ComponentCatalogAlert,View_ComponentCatalogAlert_Host_0,{},{onClearFilter:'onClearFilter'},
    ([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvY2F0YWxvZy9jb21wb25lbnRzL2FsZXJ0L2FsZXJ0Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL3BhZ2VzL2NhdGFsb2cvY29tcG9uZW50cy9hbGVydC9hbGVydC50cyIsIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL3BhZ2VzL2NhdGFsb2cvY29tcG9uZW50cy9hbGVydC9hbGVydC5odG1sIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvY2F0YWxvZy9jb21wb25lbnRzL2FsZXJ0L2FsZXJ0LnRzLkNvbXBvbmVudENhdGFsb2dBbGVydF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsItCd0LUg0L3QsNC50LTQtdC90L4g0L3QuCDQvtC00L3QvtCz0L4g0YLQvtCy0LDRgNCwLiDQn9C+0L/RgNC+0LHRg9C50YLQtSDQuNC30LzQtdC90LjRgtGMINC/0LDRgNCw0LzQtdGC0YDRiyDQv9C+0LjRgdC60LAg0LjQu9C4IDxhIGNsYXNzPVwicG9pbnRlciB0ZXh0LW5vd3JhcFwiIChjbGljayk9XCJjbGVhckZpbHRlcigpXCI+0YHQsdGA0L7RgdC40YLRjCDRhNC40LvRjNGC0YDRizwvYT4iLCI8Y2F0LWFsZXJ0PjwvY2F0LWFsZXJ0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQXNFO1VBQUE7WUFBQTtZQUFBO1lBQStCO2NBQUE7Y0FBQTtZQUFBO1lBQS9CO1VBQUEsZ0NBQXVEOzs7O29CQ0E3SDtNQUFBO3NDQUFBLFVBQUE7TUFBQTs7OzsifQ==
