/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './jumbotron';
const styles_JumbotronControl:any[] = ([] as any[]);
export const RenderType_JumbotronControl:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_JumbotronControl,data:{}});
function View_JumbotronControl_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),14,'div',([] as any[]),
      [[8,'className',0],[8,'hidden',0]],(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),11,'div',[['class','container']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n        '])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),8,'div',[['class','slogan hidden-xs-down']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n            '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['',''])),(_l()(),
          i0.ɵted((null as any),['\n            '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),2,'p',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['',' '])),(_l()(),
          i0.ɵeld(0,(null as any),(null as any),0,'i',([] as any[]),[[8,'className',
              0]],(null as any),(null as any),(null as any),(null as any))),(_l()(),
          i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵted((null as any),['\n    '])),
      (_l()(),i0.ɵted((null as any),['\n']))],(null as any),(_ck,_v) => {
    const currVal_0:any = i0.ɵinlineInterpolate(1,'slider ',_v.context.$implicit.image,
        '');
    const currVal_1:boolean = !_v.context.$implicit.show;
    _ck(_v,0,0,currVal_0,currVal_1);
    const currVal_2:any = _v.context.$implicit.title;
    _ck(_v,7,0,currVal_2);
    const currVal_3:any = _v.context.$implicit.text;
    _ck(_v,10,0,currVal_3);
    const currVal_4:any = i0.ɵinlineInterpolate(1,'fa ',_v.context.$implicit.icon,
        '');
    _ck(_v,11,0,currVal_4);
  });
}
export function View_JumbotronControl_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),
      View_JumbotronControl_1)),i0.ɵdid(802816,(null as any),0,i1.NgForOf,[i0.ViewContainerRef,
      i0.TemplateRef,i0.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any))],(_ck,
      _v) => {
    var _co:i2.JumbotronControl = _v.component;
    const currVal_0:any = _co.jumbos;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_JumbotronControl_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'jumbotron',([] as any[]),
      (null as any),(null as any),(null as any),View_JumbotronControl_0,RenderType_JumbotronControl)),
      i0.ɵdid(245760,(null as any),0,i2.JumbotronControl,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const JumbotronControlNgFactory:i0.ComponentFactory<i2.JumbotronControl> = i0.ɵccf('jumbotron',
    i2.JumbotronControl,View_JumbotronControl_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvY29udHJvbHMvanVtYm90cm9uL2p1bWJvdHJvbi5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Qcm9qZWN0cy9tYXJrZXQvbWFya2V0L2NsaWVudC93ZWIvYXBwMS9jb250cm9scy9qdW1ib3Ryb24vanVtYm90cm9uLnRzIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvY29udHJvbHMvanVtYm90cm9uL2p1bWJvdHJvbi5odG1sIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvY29udHJvbHMvanVtYm90cm9uL2p1bWJvdHJvbi50cy5KdW1ib3Ryb25Db250cm9sX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cInNsaWRlciB7e2p1bWJvLmltYWdlfX1cIiAqbmdGb3I9XCJsZXQganVtYm8gb2YganVtYm9zXCIgW2hpZGRlbl09XCIhanVtYm8uc2hvd1wiPlxyXG4gICAgPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxyXG4gICAgICAgIDxkaXYgY2xhc3M9XCJzbG9nYW4gaGlkZGVuLXhzLWRvd25cIj5cclxuICAgICAgICAgICAgPGgxPnt7anVtYm8udGl0bGV9fTwvaDE+XHJcbiAgICAgICAgICAgIDxwPnt7anVtYm8udGV4dH19IDxpIGNsYXNzPVwiZmEge3tqdW1iby5pY29ufX1cIj48L2k+PC9wPlxyXG4gICAgICAgIDwvZGl2PlxyXG4gICAgPC9kaXY+XHJcbjwvZGl2PiIsIjxqdW1ib3Ryb24+PC9qdW1ib3Ryb24+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBQSxnQkFBd0YsMkNBQ3BGO01BQUE7TUFBQSw0Q0FBdUI7TUFDbkI7VUFBQTtNQUFtQyxtREFDL0I7VUFBQTtVQUFBLDhCQUFJLHdDQUFvQjtpQkFBQSxvQ0FDeEI7VUFBQTtVQUFBLDhCQUFHLHlDQUFlO2lCQUFBO2NBQUEsOERBQXFDO2lCQUFBLGdDQUNyRDtNQUNKO0lBTkw7UUFBQTtJQUE0RDtJQUFqRSxXQUFLLFVBQTRELFNBQWpFO0lBR2dCO0lBQUE7SUFDRDtJQUFBO0lBQWtCO1FBQUE7SUFBSCxZQUFHLFNBQUg7Ozs7b0JBSjlCO01BQUEsaUNBQUE7dUNBQUE7OztJQUFvQztJQUFwQyxXQUFvQyxTQUFwQzs7OztvQkNBQTtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
