/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './specification';
const styles_ComponentViewSpecification:any[] = ([] as any[]);
export const RenderType_ComponentViewSpecification:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ComponentViewSpecification,data:{}});
function View_ComponentViewSpecification_2(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'span',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),[', ','']))],(null as any),(_ck,_v) => {
    const currVal_0:any = (<any>_v.parent).context.$implicit.unit;
    _ck(_v,1,0,currVal_0);
  });
}
function View_ComponentViewSpecification_3(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'span',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['','']))],(null as any),(_ck,_v) => {
    const currVal_0:any = (<any>_v.parent).context.$implicit.value;
    _ck(_v,1,0,currVal_0);
  });
}
function View_ComponentViewSpecification_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),10,'tr',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
      3,'td',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['',''])),(_l()(),i0.ɵand(16777216,
      (null as any),(null as any),1,(null as any),View_ComponentViewSpecification_2)),
      i0.ɵdid(16384,(null as any),0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,
          'ngIf']},(null as any)),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),
          i0.ɵeld(0,(null as any),(null as any),2,'td',([] as any[]),(null as any),
              (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵand(16777216,
          (null as any),(null as any),1,(null as any),View_ComponentViewSpecification_3)),
      i0.ɵdid(16384,(null as any),0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,
          'ngIf']},(null as any)),(_l()(),i0.ɵted((null as any),['\n    ']))],(_ck,
      _v) => {
    const currVal_1:any = _v.context.$implicit.unit;
    _ck(_v,5,0,currVal_1);
    const currVal_2:any = _v.context.$implicit.value;
    _ck(_v,9,0,currVal_2);
  },(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit.name;
    _ck(_v,3,0,currVal_0);
  });
}
export function View_ComponentViewSpecification_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Характеристики'])),
      (_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          5,'table',[['class','table table-bordered']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),3,'tbody',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_ComponentViewSpecification_1)),
      i0.ɵdid(802816,(null as any),0,i1.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,
          i0.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n'])),(_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    var _co:i2.ComponentViewSpecification = _v.component;
    const currVal_0:any = _co.parameters;
    _ck(_v,8,0,currVal_0);
  },(null as any));
}
export function View_ComponentViewSpecification_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'v-specification',
      [['class','me-info col-md-12 col-lg-6']],(null as any),(null as any),(null as any),
      View_ComponentViewSpecification_0,RenderType_ComponentViewSpecification)),i0.ɵdid(49152,
      (null as any),0,i2.ComponentViewSpecification,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const ComponentViewSpecificationNgFactory:i0.ComponentFactory<i2.ComponentViewSpecification> = i0.ɵccf('v-specification',
    i2.ComponentViewSpecification,View_ComponentViewSpecification_Host_0,{parameters:'parameters'},
    {},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvdmlldy9jb21wb25lbnRzL3NwZWNpZmljYXRpb24vc3BlY2lmaWNhdGlvbi5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Qcm9qZWN0cy9tYXJrZXQvbWFya2V0L2NsaWVudC93ZWIvYXBwMS9wYWdlcy92aWV3L2NvbXBvbmVudHMvc3BlY2lmaWNhdGlvbi9zcGVjaWZpY2F0aW9uLnRzIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvdmlldy9jb21wb25lbnRzL3NwZWNpZmljYXRpb24vc3BlY2lmaWNhdGlvbi50cy5Db21wb25lbnRWaWV3U3BlY2lmaWNhdGlvbi5odG1sIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvdmlldy9jb21wb25lbnRzL3NwZWNpZmljYXRpb24vc3BlY2lmaWNhdGlvbi50cy5Db21wb25lbnRWaWV3U3BlY2lmaWNhdGlvbl9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuPGgyPtCl0LDRgNCw0LrRgtC10YDQuNGB0YLQuNC60Lg8L2gyPlxuPHRhYmxlIGNsYXNzPVwidGFibGUgdGFibGUtYm9yZGVyZWRcIj5cbiAgICA8dHIgKm5nRm9yPVwibGV0IHBhcmFtZXRlciBvZiBwYXJhbWV0ZXJzXCI+XG4gICAgICAgIDx0ZD57e3BhcmFtZXRlci5uYW1lfX08c3BhbiAqbmdJZj1cInBhcmFtZXRlci51bml0XCI+LCB7e3BhcmFtZXRlci51bml0fX08L3NwYW4+PC90ZD5cbiAgICAgICAgPHRkPjxzcGFuICpuZ0lmPVwicGFyYW1ldGVyLnZhbHVlXCI+e3twYXJhbWV0ZXIudmFsdWV9fTwvc3Bhbj48L3RkPlxuICAgIDwvdHI+XG48L3RhYmxlPlxuIiwiPHYtc3BlY2lmaWNhdGlvbj48L3Ytc3BlY2lmaWNhdGlvbj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDSThCO01BQUEsd0VBQTZCO2FBQUE7SUFBQTtJQUFBOzs7O29CQUMvQztNQUFBLHdFQUE4QjthQUFBO0lBQUE7SUFBQTs7OztvQkFGdEM7TUFBQSx3RUFBeUM7YUFBQSxnQ0FDckM7TUFBQTtNQUFBLGdCQUFJLHdDQUFrQjtNQUFBO2FBQUE7VUFBQSx3QkFBNkQsK0NBQ25GO2lCQUFBO2NBQUEsMERBQUk7VUFBQTthQUFBO1VBQUEsd0JBQTZEOztJQURyQztJQUFOLFdBQU0sU0FBTjtJQUNaO0lBQU4sV0FBTSxTQUFOOztJQURBO0lBQUE7Ozs7b0JBSlosdUNBQ0E7TUFBQTtNQUFBLDhCQUFJO01BQW1CLHVDQUN2QjtVQUFBO1VBQUEsNENBQW9DO1VBQUEsYUFDaEM7VUFBQTtNQUFBO2FBQUE7NEJBQUEseUNBR0s7VUFBQSxTQUNEOztJQUpBO0lBQUosV0FBSSxTQUFKOzs7O29CQ0hKO01BQUE7NkVBQUEsVUFBQTtNQUFBOzs7OzsifQ==
