/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './stocks';
const styles_StocksPage:any[] = ([] as any[]);
export const RenderType_StocksPage:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_StocksPage,
    data:{}});
export function View_StocksPage_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),7,'div',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          4,'div',[['class','row']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),1,'h2',[['class','col-12']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['Все акции'])),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),
          ['\n']))],(null as any),(null as any));
}
export function View_StocksPage_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'stocks',([] as any[]),
      (null as any),(null as any),(null as any),View_StocksPage_0,RenderType_StocksPage)),
      i0.ɵdid(49152,(null as any),0,i1.StocksPage,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const StocksPageNgFactory:i0.ComponentFactory<i1.StocksPage> = i0.ɵccf('stocks',
    i1.StocksPage,View_StocksPage_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvc3RvY2tzL3N0b2Nrcy5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Qcm9qZWN0cy9tYXJrZXQvbWFya2V0L2NsaWVudC93ZWIvYXBwMS9wYWdlcy9zdG9ja3Mvc3RvY2tzLnRzIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvc3RvY2tzL3N0b2Nrcy5odG1sIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvc3RvY2tzL3N0b2Nrcy50cy5TdG9ja3NQYWdlX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxyXG4gICAgPGRpdiBjbGFzcz1cInJvd1wiPlxyXG4gICAgICAgIDxoMiBjbGFzcz1cImNvbC0xMlwiPtCS0YHQtSDQsNC60YbQuNC4PC9oMj5cclxuICAgIDwvZGl2PlxyXG48L2Rpdj4iLCI8c3RvY2tzPjwvc3RvY2tzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBdUIsMkNBQ25CO1VBQUE7VUFBQSxnQkFBaUIsK0NBQ2I7VUFBQTtVQUFBLDRDQUFtQjtVQUFBLGdCQUFjLDJDQUMvQjtVQUFBOzs7b0JDSFY7TUFBQTthQUFBOzs7OyJ9
