/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './history';
const styles_ComponentCartHistory:any[] = ([] as any[]);
export const RenderType_ComponentCartHistory:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ComponentCartHistory,data:{}});
export function View_ComponentCartHistory_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,([] as any[]),(null as any),(null as any));
}
export function View_ComponentCartHistory_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'cart-history',
      ([] as any[]),(null as any),(null as any),(null as any),View_ComponentCartHistory_0,
      RenderType_ComponentCartHistory)),i0.ɵdid(49152,(null as any),0,i1.ComponentCartHistory,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const ComponentCartHistoryNgFactory:i0.ComponentFactory<i1.ComponentCartHistory> = i0.ɵccf('cart-history',
    i1.ComponentCartHistory,View_ComponentCartHistory_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvY2FydC9jb21wb25lbnRzL2hpc3RvcnkvaGlzdG9yeS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Qcm9qZWN0cy9tYXJrZXQvbWFya2V0L2NsaWVudC93ZWIvYXBwMS9wYWdlcy9jYXJ0L2NvbXBvbmVudHMvaGlzdG9yeS9oaXN0b3J5LnRzIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvY2FydC9jb21wb25lbnRzL2hpc3RvcnkvaGlzdG9yeS50cy5Db21wb25lbnRDYXJ0SGlzdG9yeV9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxjYXJ0LWhpc3Rvcnk+PC9jYXJ0LWhpc3Rvcnk+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtxQ0FBQSxVQUFBO01BQUE7OzsifQ==
