/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../controls/navbar/navbar.ngfactory';
import * as i2 from '../controls/navbar/navbar';
import * as i3 from '../services/navbar';
import * as i4 from '../controls/jumbotron/jumbotron.ngfactory';
import * as i5 from '../controls/jumbotron/jumbotron';
import * as i6 from '../controls/menu/menu.ngfactory';
import * as i7 from '../controls/menu/menu';
import * as i8 from '@angular/router';
import * as i9 from '../controls/footer/footer.ngfactory';
import * as i10 from '../controls/footer/footer';
import * as i11 from './default';
import * as i12 from '../providers/category';
const styles_DefaultLayout:any[] = ([] as any[]);
export const RenderType_DefaultLayout:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_DefaultLayout,data:{}});
export function View_DefaultLayout_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),13,'div',[['class','sticky-content']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['\n            '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'market-navbar',
      [['class','navbar']],(null as any),(null as any),(null as any),i1.View_NavbarControl_0,
      i1.RenderType_NavbarControl)),i0.ɵdid(49152,(null as any),0,i2.NavbarControl,
      [i3.NavbarService],(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
      ['\n            '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'jumbotron',
      ([] as any[]),(null as any),(null as any),(null as any),i4.View_JumbotronControl_0,
      i4.RenderType_JumbotronControl)),i0.ɵdid(245760,(null as any),0,i5.JumbotronControl,
      ([] as any[]),(null as any),(null as any)),(_l()(),i0.ɵted((null as any),['\n            '])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),1,'market-menu',[['class','menu']],
          (null as any),(null as any),(null as any),i6.View_MenuControl_0,i6.RenderType_MenuControl)),
      i0.ɵdid(49152,(null as any),0,i7.MenuControl,([] as any[]),{categories:[0,'categories']},
          (null as any)),(_l()(),i0.ɵted((null as any),['\n            '])),(_l()(),
          i0.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),
              (null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(212992,(null as any),0,i8.RouterOutlet,[i8.ChildrenOutletContexts,i0.ViewContainerRef,
          i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'market-footer',
          ([] as any[]),(null as any),(null as any),(null as any),i9.View_FooterControl_0,
          i9.RenderType_FooterControl)),i0.ɵdid(49152,(null as any),0,i10.FooterControl,
          ([] as any[]),(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n    ']))],(_ck,_v) => {
    var _co:i11.DefaultLayout = _v.component;
    _ck(_v,7,0);
    const currVal_0:any = _co.categories;
    _ck(_v,10,0,currVal_0);
    _ck(_v,13,0);
  },(null as any));
}
export function View_DefaultLayout_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'default',[['class',
      'sticky']],(null as any),(null as any),(null as any),View_DefaultLayout_0,RenderType_DefaultLayout)),
      i0.ɵdid(114688,(null as any),0,i11.DefaultLayout,[i12.CategoryProvider],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const DefaultLayoutNgFactory:i0.ComponentFactory<i11.DefaultLayout> = i0.ɵccf('default',
    i11.DefaultLayout,View_DefaultLayout_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvbGF5b3V0cy9kZWZhdWx0Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL2xheW91dHMvZGVmYXVsdC50cyIsIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL2xheW91dHMvZGVmYXVsdC50cy5EZWZhdWx0TGF5b3V0Lmh0bWwiLCJuZzovLy9DOi9Qcm9qZWN0cy9tYXJrZXQvbWFya2V0L2NsaWVudC93ZWIvYXBwMS9sYXlvdXRzL2RlZmF1bHQudHMuRGVmYXVsdExheW91dF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8ZGl2IGNsYXNzPVwic3RpY2t5LWNvbnRlbnRcIj5cbiAgICAgICAgICAgIDxtYXJrZXQtbmF2YmFyPjwvbWFya2V0LW5hdmJhcj5cbiAgICAgICAgICAgIDxqdW1ib3Ryb24+PC9qdW1ib3Ryb24+XG4gICAgICAgICAgICA8bWFya2V0LW1lbnUgW2NhdGVnb3JpZXNdPVwiY2F0ZWdvcmllc1wiPjwvbWFya2V0LW1lbnU+XG4gICAgICAgICAgICA8cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XG4gICAgICAgIDwvZGl2PlxuICAgICAgICA8bWFya2V0LWZvb3Rlcj48L21hcmtldC1mb290ZXI+XG4gICAgIiwiPGRlZmF1bHQ+PC9kZWZhdWx0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsK0NBQ1E7TUFBQTtNQUFBLDBEQUE0QjtNQUFBLHFCQUN4QjtNQUFBO2lDQUFBLFVBQUE7TUFBQSxnREFBK0I7TUFBQSxxQkFDL0I7TUFBQTtvQ0FBQSxVQUFBO01BQUEsMkNBQXVCO01BQ3ZCO1VBQUE7YUFBQTtVQUFBLGVBQXFELG1EQUNyRDtpQkFBQTtjQUFBO2FBQUE7c0NBQUE7VUFBQSxlQUErQiwrQ0FDN0I7VUFBQSxpQkFDTjtVQUFBO3FDQUFBLFVBQUE7VUFBQSwyQ0FBK0I7VUFBQTs7SUFKM0I7SUFDYTtJQUFiLFlBQWEsU0FBYjtJQUNBOzs7O29CQ0xaO01BQUE7YUFBQTtVQUFBO0lBQUE7Ozs7In0=
