/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './maps';
import * as i2 from '@angular/common';
const styles_MapsControl:any[] = ([] as any[]);
export const RenderType_MapsControl:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_MapsControl,
    data:{}});
export function View_MapsControl_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'div',[['id','maps-container']],
      (null as any),(null as any),(null as any),(null as any),(null as any)))],(null as any),
      (null as any));
}
export function View_MapsControl_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'maps-yandex',
      ([] as any[]),(null as any),(null as any),(null as any),View_MapsControl_0,RenderType_MapsControl)),
      i0.ɵdid(245760,(null as any),0,i1.MapsControl,[i0.PLATFORM_ID,i2.DOCUMENT],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const MapsControlNgFactory:i0.ComponentFactory<i1.MapsControl> = i0.ɵccf('maps-yandex',
    i1.MapsControl,View_MapsControl_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvY29udHJvbHMvbWFwcy9tYXBzLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL2NvbnRyb2xzL21hcHMvbWFwcy50cyIsIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL2NvbnRyb2xzL21hcHMvbWFwcy5odG1sIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvY29udHJvbHMvbWFwcy9tYXBzLnRzLk1hcHNDb250cm9sX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBpZD1cIm1hcHMtY29udGFpbmVyXCI+PC9kaXY+IiwiPG1hcHMteWFuZGV4PjwvbWFwcy15YW5kZXg+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7Ozs7b0JDQUE7TUFBQTthQUFBO1VBQUE7SUFBQTs7OzsifQ==
