/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './similar';
const styles_ComponentViewSimilar:any[] = ([] as any[]);
export const RenderType_ComponentViewSimilar:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ComponentViewSimilar,data:{}});
function View_ComponentViewSimilar_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'li',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['\n       ',' ','\n    ']))],(null as any),(_ck,_v) => {
    const currVal_0:any = _v.context.index;
    const currVal_1:any = _v.context.$implicit.name;
    _ck(_v,1,0,currVal_0,currVal_1);
  });
}
export function View_ComponentViewSimilar_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),4,'ul',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),
      i0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_ComponentViewSimilar_1)),
      i0.ɵdid(802816,(null as any),0,i1.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,
          i0.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n'])),(_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    var _co:i2.ComponentViewSimilar = _v.component;
    const currVal_0:any = _co.similar;
    _ck(_v,4,0,currVal_0);
  },(null as any));
}
export function View_ComponentViewSimilar_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'v-similar',([] as any[]),
      (null as any),(null as any),(null as any),View_ComponentViewSimilar_0,RenderType_ComponentViewSimilar)),
      i0.ɵdid(49152,(null as any),0,i2.ComponentViewSimilar,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const ComponentViewSimilarNgFactory:i0.ComponentFactory<i2.ComponentViewSimilar> = i0.ɵccf('v-similar',
    i2.ComponentViewSimilar,View_ComponentViewSimilar_Host_0,{similar:'similar'},{},
    ([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvdmlldy9jb21wb25lbnRzL3NpbWlsYXIvc2ltaWxhci5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Qcm9qZWN0cy9tYXJrZXQvbWFya2V0L2NsaWVudC93ZWIvYXBwMS9wYWdlcy92aWV3L2NvbXBvbmVudHMvc2ltaWxhci9zaW1pbGFyLnRzIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvdmlldy9jb21wb25lbnRzL3NpbWlsYXIvc2ltaWxhci50cy5Db21wb25lbnRWaWV3U2ltaWxhci5odG1sIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvdmlldy9jb21wb25lbnRzL3NpbWlsYXIvc2ltaWxhci50cy5Db21wb25lbnRWaWV3U2ltaWxhcl9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuPHVsPlxuICAgIDxsaSAqbmdGb3I9XCJsZXQgcHJvZHVjdCBvZiBzaW1pbGFyOyBsZXQgaSA9IGluZGV4O1wiPlxuICAgICAgIHt7aX19IHt7cHJvZHVjdC5uYW1lfX1cbiAgICA8L2xpPlxuPC91bD5cbiIsIjx2LXNpbWlsYXI+PC92LXNpbWlsYXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0VJO01BQUEsd0VBQW9EO2FBQUE7SUFBQTtJQUFBO0lBQUE7Ozs7b0JBRnhELHVDQUNBO01BQUE7TUFBQSw4QkFBSSwyQ0FDQTthQUFBO2FBQUE7NEJBQUEseUNBRUs7VUFBQSxTQUNKOztJQUhHO0lBQUosV0FBSSxTQUFKOzs7O29CQ0ZKO01BQUE7YUFBQTtVQUFBOzs7OyJ9
