/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './components/welcome/welcome.ngfactory';
import * as i2 from './components/welcome/welcome';
import * as i3 from './specials';
import * as i4 from './components/products/products.ngfactory';
import * as i5 from './components/products/products';
import * as i6 from './components/seo/seo.ngfactory';
import * as i7 from './components/seo/seo';
import * as i8 from '../../providers/product';
import * as i9 from '../../providers/contract';
import * as i10 from '../../services/navbar';
const styles_SpecialsPage:any[] = ([] as any[]);
export const RenderType_SpecialsPage:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_SpecialsPage,
    data:{}});
export function View_SpecialsPage_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),11,'div',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'sp-welcome',[['class','row']],(null as any),(null as any),(null as any),
          i1.View_ComponentSpecialsWelcome_0,i1.RenderType_ComponentSpecialsWelcome)),
      i0.ɵdid(49152,(null as any),0,i2.ComponentSpecialsWelcome,([] as any[]),(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),1,'sp-products',[['class','row']],(null as any),
          [[(null as any),'onPostPosition']],(_v,en,$event) => {
            var ad:boolean = true;
            var _co:i3.SpecialsPage = _v.component;
            if (('onPostPosition' === en)) {
              const pd_0:any = ((<any>_co.postPosition($event)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },i4.View_ComponentSpecialsProducts_0,i4.RenderType_ComponentSpecialsProducts)),
      i0.ɵdid(49152,(null as any),0,i5.ComponentSpecialsProducts,([] as any[]),{products:[0,
          'products']},{onPostPosition:'onPostPosition'}),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),1,'sp-seo',[['class','row']],(null as any),(null as any),
          (null as any),i6.View_ComponentSpecialsSeo_0,i6.RenderType_ComponentSpecialsSeo)),
      i0.ɵdid(49152,(null as any),0,i7.ComponentSpecialsSeo,([] as any[]),(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    var _co:i3.SpecialsPage = _v.component;
    const currVal_0:any = _co.products;
    _ck(_v,6,0,currVal_0);
  },(null as any));
}
export function View_SpecialsPage_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'specials',([] as any[]),
      (null as any),(null as any),(null as any),View_SpecialsPage_0,RenderType_SpecialsPage)),
      i0.ɵdid(114688,(null as any),0,i3.SpecialsPage,[i8.ProductProvider,i9.ContractProvider,
          i10.NavbarService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const SpecialsPageNgFactory:i0.ComponentFactory<i3.SpecialsPage> = i0.ɵccf('specials',
    i3.SpecialsPage,View_SpecialsPage_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvc3BlY2lhbHMvc3BlY2lhbHMubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvc3BlY2lhbHMvc3BlY2lhbHMudHMiLCJuZzovLy9DOi9Qcm9qZWN0cy9tYXJrZXQvbWFya2V0L2NsaWVudC93ZWIvYXBwMS9wYWdlcy9zcGVjaWFscy9zcGVjaWFscy5odG1sIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvc3BlY2lhbHMvc3BlY2lhbHMudHMuU3BlY2lhbHNQYWdlX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxyXG4gICAgPHNwLXdlbGNvbWUgY2xhc3M9XCJyb3dcIj48L3NwLXdlbGNvbWU+XHJcbiAgICA8c3AtcHJvZHVjdHMgY2xhc3M9XCJyb3dcIiBbcHJvZHVjdHNdPVwicHJvZHVjdHNcIiAob25Qb3N0UG9zaXRpb24pPVwicG9zdFBvc2l0aW9uKCRldmVudClcIj48L3NwLXByb2R1Y3RzPlxyXG4gICAgPCEtLTxzcC1wcm9tbyBjbGFzcz1cInJvd1wiPjwvc3AtcHJvbW8+LS0+XHJcbiAgICA8c3Atc2VvIGNsYXNzPVwicm93XCI+PC9zcC1zZW8+XHJcbjwvZGl2PiIsIjxzcGVjaWFscz48L3NwZWNpYWxzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBdUIsMkNBQ25CO1VBQUE7bUZBQUE7YUFBQTtVQUFBLGVBQXFDLDJDQUNyQztVQUFBO1VBQUE7WUFBQTtZQUFBO1lBQStDO2NBQUE7Y0FBQTtZQUFBO1lBQS9DO1VBQUE7YUFBQTtVQUFBLGdEQUFxRztVQUFBLGFBQzdELDJDQUN4QztVQUFBO1VBQUE7YUFBQTtVQUFBLGVBQTZCOztJQUZKO0lBQXpCLFdBQXlCLFNBQXpCOzs7O29CQ0ZKO01BQUE7YUFBQTsyQkFBQTtJQUFBOzs7OyJ9
