/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './photo';
const styles_ComponentViewPhoto:any[] = ([] as any[]);
export const RenderType_ComponentViewPhoto:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ComponentViewPhoto,data:{}});
function View_ComponentViewPhoto_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'img',[['class',
      'img-responsive']],[[8,'src',4]],(null as any),(null as any),(null as any),(null as any)))],
      (null as any),(_ck,_v) => {
        var _co:any = _v.component;
        const currVal_0:any = i0.ɵinlineInterpolate(1,'',((('/photos/' + _co.productId) + '/l_') + _co.image),
            '');
        _ck(_v,0,0,currVal_0);
      });
}
export function View_ComponentViewPhoto_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵand(16777216,
      (null as any),(null as any),1,(null as any),View_ComponentViewPhoto_1)),i0.ɵdid(16384,
      (null as any),0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,'ngIf']},
      (null as any)),(_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    var _co:i2.ComponentViewPhoto = _v.component;
    const currVal_0:any = _co.image;
    _ck(_v,2,0,currVal_0);
  },(null as any));
}
export function View_ComponentViewPhoto_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'v-photo',[['class',
      'me-image']],(null as any),(null as any),(null as any),View_ComponentViewPhoto_0,
      RenderType_ComponentViewPhoto)),i0.ɵdid(49152,(null as any),0,i2.ComponentViewPhoto,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const ComponentViewPhotoNgFactory:i0.ComponentFactory<i2.ComponentViewPhoto> = i0.ɵccf('v-photo',
    i2.ComponentViewPhoto,View_ComponentViewPhoto_Host_0,{productId:'productId',image:'image'},
    {},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvcGFnZXMvdmlldy9jb21wb25lbnRzL3Bob3RvL3Bob3RvLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL3BhZ2VzL3ZpZXcvY29tcG9uZW50cy9waG90by9waG90by50cyIsIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL3BhZ2VzL3ZpZXcvY29tcG9uZW50cy9waG90by9waG90by50cy5Db21wb25lbnRWaWV3UGhvdG8uaHRtbCIsIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL3BhZ2VzL3ZpZXcvY29tcG9uZW50cy9waG90by9waG90by50cy5Db21wb25lbnRWaWV3UGhvdG9fSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbjxpbWcgKm5nSWY9XCJpbWFnZVwiIGNsYXNzPVwiaW1nLXJlc3BvbnNpdmVcIiBzcmM9XCJ7eycvcGhvdG9zLycrcHJvZHVjdElkKyAnL2xfJysgaW1hZ2V9fVwiPlxuIiwiPHYtcGhvdG8+PC92LXBob3RvPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNDQTtNQUFBOzs7UUFBMEM7WUFBQTtRQUExQyxXQUEwQyxTQUExQzs7OztvQkFEQSx1Q0FDQTtNQUFBLCtFQUFBO01BQUE7TUFBQSxlQUF1Rjs7SUFBbEY7SUFBTCxXQUFLLFNBQUw7Ozs7b0JDREE7TUFBQTttQ0FBQSxVQUFBO01BQUE7Ozs7In0=
