/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './pager';
const styles_PagerControl:any[] = ([] as any[]);
export const RenderType_PagerControl:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_PagerControl,
    data:{}});
function View_PagerControl_2(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),6,'li',[['class',
      'page-item']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(278528,(null as any),0,i1.NgClass,[i0.IterableDiffers,i0.KeyValueDiffers,
          i0.ElementRef,i0.Renderer],{klass:[0,'klass'],ngClass:[1,'ngClass']},(null as any)),
      i0.ɵpod({'active':0}),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),
          i0.ɵeld(0,(null as any),(null as any),1,'a',[['class','page-link']],(null as any),
              [[(null as any),'click']],(_v,en,$event) => {
                var ad:boolean = true;
                var _co:any = _v.component;
                if (('click' === en)) {
                  const pd_0:any = ((<any>_co.pageChange($event,_v.context.$implicit)) !== false);
                  ad = (pd_0 && ad);
                }
                return ad;
              },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['',''])),
      (_l()(),i0.ɵted((null as any),['\n    ']))],(_ck,_v) => {
    var _co:any = _v.component;
    const currVal_0:any = 'page-item';
    const currVal_1:any = _ck(_v,2,0,(_v.context.$implicit == _co.currentPage));
    _ck(_v,1,0,currVal_0,currVal_1);
  },(_ck,_v) => {
    const currVal_2:any = _v.context.$implicit;
    _ck(_v,5,0,currVal_2);
  });
}
function View_PagerControl_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'ul',[['class',
      'pagination']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵand(16777216,(null as any),
          (null as any),1,(null as any),View_PagerControl_2)),i0.ɵdid(802816,(null as any),
          0,i1.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],{ngForOf:[0,
              'ngForOf']},(null as any)),(_l()(),i0.ɵted((null as any),['\n']))],(_ck,
      _v) => {
    var _co:any = _v.component;
    const currVal_0:any = _co.pages;
    _ck(_v,3,0,currVal_0);
  },(null as any));
}
export function View_PagerControl_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),
      View_PagerControl_1)),i0.ɵdid(16384,(null as any),0,i1.NgIf,[i0.ViewContainerRef,
      i0.TemplateRef],{ngIf:[0,'ngIf']},(null as any))],(_ck,_v) => {
    var _co:i2.PagerControl = _v.component;
    const currVal_0:any = (_co.pages.length > 1);
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_PagerControl_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'pager',([] as any[]),
      (null as any),(null as any),(null as any),View_PagerControl_0,RenderType_PagerControl)),
      i0.ɵdid(49152,(null as any),0,i2.PagerControl,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const PagerControlNgFactory:i0.ComponentFactory<i2.PagerControl> = i0.ɵccf('pager',
    i2.PagerControl,View_PagerControl_Host_0,{category:'category',size:'size',itemsPerPage:'itemsPerPage'},
    {onPageChange:'onPageChange'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvY29udHJvbHMvcGFnZXIvcGFnZXIubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvY29udHJvbHMvcGFnZXIvcGFnZXIudHMiLCJuZzovLy9DOi9Qcm9qZWN0cy9tYXJrZXQvbWFya2V0L2NsaWVudC93ZWIvYXBwMS9jb250cm9scy9wYWdlci9wYWdlci5odG1sIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvY29udHJvbHMvcGFnZXIvcGFnZXIudHMuUGFnZXJDb250cm9sX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHVsIGNsYXNzPVwicGFnaW5hdGlvblwiICpuZ0lmPVwicGFnZXMubGVuZ3RoPjFcIj5cclxuICAgIDxsaSBjbGFzcz1cInBhZ2UtaXRlbVwiIFtuZ0NsYXNzXT1cInsnYWN0aXZlJzpwYWdlPT1jdXJyZW50UGFnZX1cIiAqbmdGb3I9XCJsZXQgcGFnZSBvZiBwYWdlc1wiPlxyXG4gICAgICAgIDxhIGNsYXNzPVwicGFnZS1saW5rXCIgKGNsaWNrKT1cInBhZ2VDaGFuZ2UoJGV2ZW50LCBwYWdlKVwiPnt7cGFnZX19PC9hPlxyXG4gICAgPC9saT5cclxuPC91bD4iLCI8cGFnZXI+PC9wYWdlcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQ0k7TUFBQTthQUFBO21DQUFBO2FBQXNCLGVBQW9FLCtDQUN0RjtpQkFBQTtjQUFBO2dCQUFBO2dCQUFBO2dCQUFxQjtrQkFBQTtrQkFBQTtnQkFBQTtnQkFBckI7Y0FBQSxnQ0FBd0Q7TUFBWTs7SUFEcEU7SUFBa0I7SUFBdEIsV0FBSSxVQUFrQixTQUF0Qjs7SUFDNEQ7SUFBQTs7OztvQkFGaEU7TUFBQTtNQUE4QywyQ0FDMUM7VUFBQSwyREFBQTtVQUFBO2NBQUEsMkJBRUs7OztJQUYwRDtJQUEvRCxXQUErRCxTQUEvRDs7OztvQkFESjtNQUFBLDZCQUFBO29CQUFBOztJQUF1QjtJQUF2QixXQUF1QixTQUF2Qjs7OztvQkNBQTtNQUFBO2FBQUE7Ozs7OyJ9
