/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './module';
import * as i2 from '../layouts/root';
import * as i3 from '../layouts/default.ngfactory';
import * as i4 from '../pages/specials/specials.ngfactory';
import * as i5 from '../pages/delivery/delivery.ngfactory';
import * as i6 from '../pages/contacts/contacts.ngfactory';
import * as i7 from '../pages/cart/cart/cart.ngfactory';
import * as i8 from '../pages/cart/history/history.ngfactory';
import * as i9 from '../pages/stocks/stocks.ngfactory';
import * as i10 from '../pages/notfound/page-notfound.ngfactory';
import * as i11 from '../pages/view/view.ngfactory';
import * as i12 from '../pages/catalog/catalog.ngfactory';
import * as i13 from '../layouts/root.ngfactory';
import * as i14 from '@angular/common';
import * as i15 from '@angular/platform-browser';
import * as i16 from '@angular/animations/browser';
import * as i17 from '@angular/platform-browser/animations';
import * as i18 from '@angular/animations';
import * as i19 from '@angular/forms';
import * as i20 from '@angular/router';
import * as i21 from '../providers/category';
import * as i22 from '@angular/http';
import * as i23 from '../providers/parameter';
import * as i24 from '../providers/product';
import * as i25 from '../services/parameters';
import * as i26 from '../services/sort';
import * as i27 from '../services/config';
import * as i28 from '../providers/settings';
import * as i29 from '../providers/index';
import * as i30 from '../layouts/default';
import * as i31 from '../pages/specials/specials';
import * as i32 from '../pages/delivery/delivery';
import * as i33 from '../pages/contacts/contacts';
import * as i34 from '../pages/cart/cart/cart';
import * as i35 from '../pages/cart/history/history';
import * as i36 from '../pages/stocks/stocks';
import * as i37 from '../pages/notfound/page-notfound';
import * as i38 from '../pages/view/view';
import * as i39 from '../pages/catalog/catalog';
import * as i40 from '../controls/module';
import * as i41 from '../pages/specials/components/module';
import * as i42 from '../pages/view/components/module';
import * as i43 from '../pages/cart/components/module';
import * as i44 from '../pages/catalog/components/module';
import * as i45 from '../pages/module';
import * as i46 from '../layouts/module';
import * as i47 from '../services/global';
import * as i48 from '../providers/contract';
import * as i49 from '../services/navbar';
import * as i50 from '../module';
export const BrowserAppModuleNgFactory:i0.NgModuleFactory<i1.BrowserAppModule> = i0.ɵcmf(i1.BrowserAppModule,
    [i2.RootLayout],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.DefaultLayoutNgFactory,i4.SpecialsPageNgFactory,i5.DeliveryPageNgFactory,
              i6.ContactsPageNgFactory,i7.CartPageNgFactory,i8.HistoryPageNgFactory,
              i9.StocksPageNgFactory,i10.NotfoundPageNgFactory,i11.ViewPageNgFactory,
              i12.CatalogPageNgFactory,i13.RootLayoutNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),
          i0.ɵmpd(4608,i14.NgLocalization,i14.NgLocaleLocalization,[i0.LOCALE_ID]),
          i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
              i0.ɵl,([] as any[])),i0.ɵmpd(4608,i15.DomSanitizer,i15.ɵe,[i14.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i15.DomSanitizer]),i0.ɵmpd(4608,
              i15.HAMMER_GESTURE_CONFIG,i15.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i15.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i15.ɵDomEventsPlugin(p0_0),new i15.ɵKeyEventsPlugin(p1_0),
                    new i15.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i14.DOCUMENT,i14.DOCUMENT,i14.DOCUMENT,i15.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i15.EventManager,i15.EventManager,[i15.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i15.ɵDomSharedStylesHost,i15.ɵDomSharedStylesHost,
              [i14.DOCUMENT]),i0.ɵmpd(4608,i15.ɵDomRendererFactory2,i15.ɵDomRendererFactory2,
              [i15.EventManager,i15.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i16.AnimationDriver,
              i17.ɵc,([] as any[])),i0.ɵmpd(5120,i16.ɵAnimationStyleNormalizer,i17.ɵd,
              ([] as any[])),i0.ɵmpd(4608,i16.ɵAnimationEngine,i17.ɵb,[i16.AnimationDriver,
              i16.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i17.ɵe,
              [i15.ɵDomRendererFactory2,i16.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(6144,
              i15.ɵSharedStylesHost,(null as any),[i15.ɵDomSharedStylesHost]),i0.ɵmpd(4608,
              i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i15.Meta,i15.Meta,
              [i14.DOCUMENT]),i0.ɵmpd(4608,i15.Title,i15.Title,[i14.DOCUMENT]),i0.ɵmpd(4608,
              i18.AnimationBuilder,i17.ɵBrowserAnimationBuilder,[i0.RendererFactory2,
                  i15.DOCUMENT]),i0.ɵmpd(4608,i19.ɵi,i19.ɵi,([] as any[])),i0.ɵmpd(5120,
              i20.ActivatedRoute,i20.ɵf,[i20.Router]),i0.ɵmpd(4608,i20.NoPreloading,
              i20.NoPreloading,([] as any[])),i0.ɵmpd(6144,i20.PreloadingStrategy,
              (null as any),[i20.NoPreloading]),i0.ɵmpd(135680,i20.RouterPreloader,
              i20.RouterPreloader,[i20.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i20.PreloadingStrategy]),i0.ɵmpd(4608,i20.PreloadAllModules,
              i20.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i20.ROUTER_INITIALIZER,
              i20.ɵi,[i20.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i20.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i21.CategoryProvider,i21.CategoryProvider,
              [i22.Http]),i0.ɵmpd(4608,i23.ParameterProvider,i23.ParameterProvider,
              [i22.Http]),i0.ɵmpd(4608,i24.ProductProvider,i24.ProductProvider,[i22.Http]),
          i0.ɵmpd(4608,i25.ParametersService,i25.ParametersService,([] as any[])),
          i0.ɵmpd(4608,i26.SortingService,i26.SortingService,([] as any[])),i0.ɵmpd(512,
              i14.CommonModule,i14.CommonModule,([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,
              i15.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,() => {
            return [i20.ɵb()];
          },([] as any[])),i0.ɵmpd(512,i20.ɵg,i20.ɵg,[i0.Injector]),i0.ɵmpd(512,i22.BrowserXhr,
              i22.BrowserXhr,([] as any[])),i0.ɵmpd(512,i22.ResponseOptions,i22.BaseResponseOptions,
              ([] as any[])),i0.ɵmpd(1024,i22.XSRFStrategy,i22.ɵb,([] as any[])),i0.ɵmpd(512,
              i22.XHRBackend,i22.XHRBackend,[i22.BrowserXhr,i22.ResponseOptions,i22.XSRFStrategy]),
          i0.ɵmpd(512,i22.RequestOptions,i22.BaseRequestOptions,([] as any[])),i0.ɵmpd(1024,
              i22.Http,i22.ɵc,[i22.XHRBackend,i22.RequestOptions]),i0.ɵmpd(512,i27.ConfigService,
              i27.ConfigService,([] as any[])),i0.ɵmpd(512,i28.SettingsProvider,i28.SettingsProvider,
              [i22.Http,i27.ConfigService]),i0.ɵmpd(256,i0.APP_ID,'BD484954-6626-4699-86BD-AF9CA21F0DE8',
              ([] as any[])),i0.ɵmpd(2048,i15.ɵTRANSITION_ID,(null as any),[i0.APP_ID]),
          i0.ɵmpd(1024,i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any,p2_0:any,p3_0:any,
              p3_1:any,p3_2:any) => {
            return [i15.ɵc(p0_0,p0_1),i20.ɵh(p1_0),i29.SettingsFactory(p2_0),i15.ɵf(p3_0,
                p3_1,p3_2)];
          },[[2,i15.NgProbeToken],[2,i0.NgProbeToken],i20.ɵg,i28.SettingsProvider,
              i15.ɵTRANSITION_ID,i14.DOCUMENT,i0.Injector]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i15.BrowserModule,i15.BrowserModule,[[3,i15.BrowserModule]]),
          i0.ɵmpd(512,i17.BrowserAnimationsModule,i17.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i22.HttpModule,i22.HttpModule,([] as any[])),i0.ɵmpd(1024,i20.ɵa,
              i20.ɵd,[[3,i20.Router]]),i0.ɵmpd(512,i20.UrlSerializer,i20.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i20.ChildrenOutletContexts,i20.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i20.ROUTER_CONFIGURATION,{},([] as any[])),
          i0.ɵmpd(1024,i14.LocationStrategy,i20.ɵc,[i14.PlatformLocation,[2,i14.APP_BASE_HREF],
              i20.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i14.Location,i14.Location,[i14.LocationStrategy]),
          i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i20.ROUTES,() => {
            return [[{path:'',component:i30.DefaultLayout,children:[{path:'',component:i31.SpecialsPage},
                {path:'delivery',component:i32.DeliveryPage},{path:'contacts',component:i33.ContactsPage},
                {path:'cart',component:i34.CartPage},{path:'cart/:contract',component:i35.HistoryPage},
                {path:'stocks',component:i36.StocksPage},{path:'notfound',component:i37.NotfoundPage},
                {path:':categoryName/:productId',component:i38.ViewPage},{path:':categoryName',
                    component:i39.CatalogPage},{path:'**',redirectTo:'/notfound'}]}]];
          },([] as any[])),i0.ɵmpd(1024,i20.Router,i20.ɵe,[i0.ApplicationRef,i20.UrlSerializer,
              i20.ChildrenOutletContexts,i14.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i20.ROUTES,i20.ROUTER_CONFIGURATION,[2,i20.UrlHandlingStrategy],
              [2,i20.RouteReuseStrategy]]),i0.ɵmpd(512,i20.RouterModule,i20.RouterModule,
              [[2,i20.ɵa],[2,i20.Router]]),i0.ɵmpd(512,i40.ControlsModule,i40.ControlsModule,
              ([] as any[])),i0.ɵmpd(512,i41.ModuleComponentsSpecials,i41.ModuleComponentsSpecials,
              ([] as any[])),i0.ɵmpd(512,i42.ModuleComponentsView,i42.ModuleComponentsView,
              ([] as any[])),i0.ɵmpd(512,i19.ɵba,i19.ɵba,([] as any[])),i0.ɵmpd(512,
              i19.FormsModule,i19.FormsModule,([] as any[])),i0.ɵmpd(512,i43.ModuleComponentsCart,
              i43.ModuleComponentsCart,([] as any[])),i0.ɵmpd(512,i44.ModuleComponentsCatalog,
              i44.ModuleComponentsCatalog,([] as any[])),i0.ɵmpd(512,i45.PagesModule,
              i45.PagesModule,([] as any[])),i0.ɵmpd(512,i46.LayoutsModule,i46.LayoutsModule,
              ([] as any[])),i0.ɵmpd(512,i47.GlobalService,i47.GlobalService,([] as any[])),
          i0.ɵmpd(512,i48.ContractProvider,i48.ContractProvider,[i22.Http]),i0.ɵmpd(512,
              i49.NavbarService,i49.NavbarService,([] as any[])),i0.ɵmpd(512,i50.ApplicationModule,
              i50.ApplicationModule,[i20.Router,i47.GlobalService,i48.ContractProvider,
                  i49.NavbarService]),i0.ɵmpd(512,i1.BrowserAppModule,i1.BrowserAppModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvX2Jyb3dzZXIvbW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1Byb2plY3RzL21hcmtldC9tYXJrZXQvY2xpZW50L3dlYi9hcHAxL19icm93c2VyL21vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
