/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '@angular/common';
import * as i3 from './navbar-item';
const styles_NavbarItemComponent:any[] = ([] as any[]);
export const RenderType_NavbarItemComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_NavbarItemComponent,data:{}});
export function View_NavbarItemComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),6,'a',[['class',
      'navbar-item__link'],['routerLinkActive','active']],[[1,'target',0],[8,'href',
      4]],[[(null as any),'click']],(_v,en,$event) => {
    var ad:boolean = true;
    if (('click' === en)) {
      const pd_0:any = ((<any>i0.ɵnov(_v,1).onClick($event.button,$event.ctrlKey,$event.metaKey,
          $event.shiftKey)) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any))),i0.ɵdid(671744,[[2,4]],0,i1.RouterLinkWithHref,[i1.Router,
      i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},(null as any)),
      i0.ɵdid(1720320,(null as any),2,i1.RouterLinkActive,[i1.Router,i0.ElementRef,
          i0.Renderer2,i0.ChangeDetectorRef],{routerLinkActive:[0,'routerLinkActive']},
          (null as any)),i0.ɵqud(603979776,1,{links:1}),i0.ɵqud(603979776,2,{linksWithHrefs:1}),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),0,'i',([] as any[]),[[8,'className',
          0]],(null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['',''])),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'b',[['class','navbar-item__label']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['','']))],(_ck,_v) => {
    var _co:i3.NavbarItemComponent = _v.component;
    const currVal_2:any = i0.ɵinlineInterpolate(1,'',_co.data.link,'');
    _ck(_v,1,0,currVal_2);
    const currVal_3:any = 'active';
    _ck(_v,2,0,currVal_3);
  },(_ck,_v) => {
    var _co:i3.NavbarItemComponent = _v.component;
    const currVal_0:any = i0.ɵnov(_v,1).target;
    const currVal_1:any = i0.ɵnov(_v,1).href;
    _ck(_v,0,0,currVal_0,currVal_1);
    const currVal_4:any = i0.ɵinlineInterpolate(1,'fa ',_co.data.icon,' rgap hidden-xs-down');
    _ck(_v,5,0,currVal_4);
    const currVal_5:any = _co.data.name;
    _ck(_v,6,0,currVal_5);
    const currVal_6:any = _co.data.label;
    _ck(_v,9,0,currVal_6);
  });
}
export function View_NavbarItemComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'navbar-item',
      ([] as any[]),(null as any),(null as any),(null as any),View_NavbarItemComponent_0,
      RenderType_NavbarItemComponent)),i0.ɵdid(49152,(null as any),0,i3.NavbarItemComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const NavbarItemComponentNgFactory:i0.ComponentFactory<i3.NavbarItemComponent> = i0.ɵccf('navbar-item',
    i3.NavbarItemComponent,View_NavbarItemComponent_Host_0,{data:'data'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvY29udHJvbHMvbmF2YmFyL2NvbXBvbmVudHMvbmF2YmFyLWl0ZW0vbmF2YmFyLWl0ZW0ubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvY29udHJvbHMvbmF2YmFyL2NvbXBvbmVudHMvbmF2YmFyLWl0ZW0vbmF2YmFyLWl0ZW0udHMiLCJuZzovLy9DOi9Qcm9qZWN0cy9tYXJrZXQvbWFya2V0L2NsaWVudC93ZWIvYXBwMS9jb250cm9scy9uYXZiYXIvY29tcG9uZW50cy9uYXZiYXItaXRlbS9uYXZiYXItaXRlbS5odG1sIiwibmc6Ly8vQzovUHJvamVjdHMvbWFya2V0L21hcmtldC9jbGllbnQvd2ViL2FwcDEvY29udHJvbHMvbmF2YmFyL2NvbXBvbmVudHMvbmF2YmFyLWl0ZW0vbmF2YmFyLWl0ZW0udHMuTmF2YmFySXRlbUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxhIGNsYXNzPVwibmF2YmFyLWl0ZW1fX2xpbmtcIiByb3V0ZXJMaW5rQWN0aXZlPVwiYWN0aXZlXCIgcm91dGVyTGluaz1cInt7ZGF0YS5saW5rfX1cIj48aSBjbGFzcz1cImZhIHt7ZGF0YS5pY29ufX0gcmdhcCBoaWRkZW4teHMtZG93blwiPjwvaT57e2RhdGEubmFtZX19PC9hPlxyXG48YiBjbGFzcz1cIm5hdmJhci1pdGVtX19sYWJlbFwiPnt7ZGF0YS5sYWJlbH19PC9iPiIsIjxuYXZiYXItaXRlbT48L25hdmJhci1pdGVtPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFBO0lBQUE7SUFBQTtNQUFBO1VBQUE7TUFBQTtJQUFBO0lBQUE7RUFBQSx1Q0FBQTsyQ0FBQTthQUFBOzJDQUFBO1VBQUE7TUFBa0Y7VUFBQSw4REFBb0Q7VUFBQSxVQUFpQix1Q0FDdko7VUFBQTtVQUFBLDRDQUE4QjtVQUFBOztJQUR5QjtJQUF2RCxXQUF1RCxTQUF2RDtJQUE2QjtJQUE3QixXQUE2QixTQUE3Qjs7O0lBQUE7SUFBQTtJQUFBLFdBQUEsbUJBQUE7SUFBcUY7SUFBSCxXQUFHLFNBQUg7SUFBb0Q7SUFBQTtJQUN4RztJQUFBOzs7O29CQ0Q5QjtNQUFBO29DQUFBLFVBQUE7TUFBQTs7OyJ9
